package file_utils;

public enum Categories {
	FIRST, LAST, BOOK_TITLE, BOOK_ISBN, ID, PHONE, MAJOR, SALARY, COURSES_TO_TAKE, COURSES_TAKING, COURSES_TAKEN, PRICE,
	ROOM_NUMBER, BUILDING_NAME, NUMBER_OF_SEATS, NUMBER_OF_COMPUTERS, PROJECTOR_OR_NOT, COURSES_TAUGHT;
}
